#(Como se presenta en el dropdown, como lo usaremos en el prompt.)
super_heroines = [
                  ("Batichica", "Batgirl"),
                  ("Black Widow", "Black Widow"),
                  ("Bruja Escarlata", "Scarlet Witch"),
                  ("Capitana Marvel", "Captain Marvel"),
                  ("Elektra", "Elektra with katana"),
                  ("Gatúbela", "Catwoman"),
                  ("Harley Quinn"),   
                  ("Hiedra Venenosa", "Poison Ivy"),
                  ("Jean Grey (X-Men)", "Marvel's Jean Grey"),  
                  ("Mera (Aquaman)", "Mera"),
                  ("Mujer Maravilla", "Wonder Woman"),
                  ("Powergirl"), 
                  ("Psylocke", "Psylocke with katana"),
                  ("She-Hulk"),
                  ("Superchica", "Supergirl"),                  
                  #("Xmen Rogue", "Xmen Titania"), 
                  #("Gata Negra", "Marvel's Black Cat"), 
                  #("Nebula de Guardianes de la Galaxia", "Guardians of the Galaxy Bald Nebula"),
                  #("Mujer Araña", "Spiderwoman"),                    
                  #("Xmen Jubilee"),
                  #("Reina Blanca", "White Queen Emma Frost"), #OK! 
                  #("Domino", "Marvel's Domino"),                                        
                  ]

super_heroes = [                
                  ("Hellboy"),
                  ("Wolverine", "Xmen Wolverine"),
                  ("Deadpool"),
                  ("Bishop"),
                  ("Xmen Bishop"),
                  ("Marvel Bishop"),
                  ("Marvel's Bishop"),
                  ("Daredevil"),
                  ("Antorcha Humana", "Human Torch"),
                  ("Aquaman"),
                  ("Batman"),
                  ("Capitán America", "Captain America"),
                  ("Dr.Strange"),
                  ("Flash", "The Flash"),
                  ("Hawkeye"), 
                  ("Ironman"),
                  ("Joker"),
                  ("Joker", "The Joker"),
                  ("Linterna Verde", "Green Lantern"),
                  ("Punisher"),             
                  ("Shazam"),
                  ("StarLord"),
                  ("Superman"),     
                  ("Spiderman", "Spiderman"),  
                  ("Xmen"),
                  ("Xmen Beast"),
                  ("Xmen Iceman"), 
                  ("Xmen Archangel"),  
                  ("War Machine"),   
                  # ("Flash Gordon"),                
                  # ("Hulk", "Hulk with green face"), ######                    
                  # ("Peter Parker"),
                  # ("Hombre Araña sin máscara", "Spiderman Peter Parker"), #OK
                  # ("Flash"),                  
                  # ("Robin"),
                  # ("Robin Sin Máscara", "Unmasked Robin"),
                  # ("Robin", "DC's Robin"),
                  # ("Ozymandias de Watchen", "Watchmen Ozymandias"),                  
                  # ("Superheroe sin máscara", "Unmasked Superhero"),  
                  # ("Colossus", "Colossus"),
                  # ("Guasón", "The Joker"), 
                  # ("Guasón", "The Joker with suit"), 
                  # ("Nick Fury"),
                  # ("Venom", "Black Venom"),
                  # ("Joker"),
                  # ("Venom", "Marvel's Black Venom"),
                  # ("Carnage"),
                  # ("Carnage", "Marvel's Carnage"),                  
                  # ("Falcon", "Marvel's Falcon"),                    
                  # ("Vision", "Avengers Vision"),
                  # ("Fantastic Four", "Marvel's Mr. Fantastic with a 4 in his chest"),
                  # ("Lobo"),
                  # ("Lobo", "DC's Lobo"),
                  # ("Lobo", "DC's Universe Lobo"),                  
                  # ("Namor", "Marvel's Namor")             
                  ]