super_heroines = [
                  ("Avispa (Wasp)", "The Wasp"),
                  ("Batichica", "Batgirl"),
                  ("Black Widow", "Black Widow"),
                  ("Bruja Escarlata", "Scarlet Witch"),
                  ("Capitana Marvel", "Captain Marvel"),
                  ("Elektra", "Elektra with katana"),
                  ("Gamora (Guardianes de la Galaxia)", "Guardians of the Galaxy Gamora"),
                  ("Gatúbela", "Catwoman"),
                  ("Harley Quinn"),   
                  ("Hiedra Venenosa", "Poison Ivy"),
                  ("Jean Grey (X-Men)", "Marvel's Jean Grey"),
                  ("Mantis (Guardianes de la Galaxia)", "Guardians of the Galaxy Mantis with antennae in her forehead"),  
                  ("Mera (Aquaman)", "Mera"),
                  ("Mujer Maravilla", "Wonder Woman"),
                  ("Powergirl"), 
                  ("Psylocke", "Psylocke with katana"),
                  ("Reina Blanca", "White Queen Emma Frost"), #OK! #Under Supervisión.
                  ("She-Hulk"),
                  ("Superchica", "Supergirl"),                  
                  #("Xmen Rogue", "Xmen Titania"),                                      
                  ]

super_heroes = [
                ("Antorcha Humana", "Human Torch"), 
                ("Arcángel (X-men)", "Xmen Archangel with wings spread"), #Checar
                ("Aquaman"),
                ("Batman"),
                ("Capitán America", "Captain America"),
                ("Dr.Strange"),
                ("Flash", "The Flash"),
                ("Hawkeye"),
                ("Iceman", "Xmen Iceman"), 
                ("Ironman"),
                ("Linterna Verde", "Green Lantern"),
                ("Nightcrawwler", "Xmen Nightcrawler"),
                ("Punisher"),             
                ("Shazam"),
                ("StarLord"),
                ("Superman"),     
                ("Spiderman", "Spiderman"),
                ("Xmen"), #El problema en anime particularmente es que salen muchos.  
                ("War Machine"),                
                ("Wolverine"),
                # ("Hulk", "Hulk with green face"), ######                    
                # ("Peter Parker"),
                # ("Flash"),                  
                # ("Robin"),                       
                # ("Colossus", "Colossus"),
                # ("Guasón", "The Joker"), 
                # ("Guasón", "The Joker with suit"), 
                # ("Nick Fury"),
                # ("Venom", "Black Venom"),
                # ("Joker"),
                # ("Venom", "Marvel's Black Venom"),
                # ("Carnage"),
                # ("Carnage", "Marvel's Carnage"),                  
                # ("Falcon", "Marvel's Falcon"),                    
                # ("Vision", "Avengers Vision"),
                # ("Fantastic Four", "Marvel's Mr. Fantastic with a 4 in his chest"),
                # ("Lobo"),
                # ("Lobo", "DC's Lobo"),
                # ("Lobo", "DC's Universe Lobo"),                  
                # ("Namor", "Marvel's Namor")             
                  ]