# super_heroines = [
#                   ("cat", "gato"),
#                   ("dog", "perro"),
#                   ("bird", "ave")
#                   ]

#(Como se presenta en el dropdown, como lo usaremos en el prompt.)
super_heroines = [
                  ("Batichica", "Batgirl"),
                #   ("Bruce Wayne Batgirl", "Bruce Wayne Batgirl"), 
                #   ("Batichica sin máscara", "Unmasked Batgirl"),
                  ("Mujer Maravilla", "Wonder Woman"),
                #   ("Xmen Rogue", "Xmen Titania"),
                #   ("Gata Negra", "Marvel's Black Cat"), 
                  ("Bruja Escarlata", "Scarlet Witch"),
                  ("Capitana Marvel", "Captain Marvel"),
                #   ("Nebula de Guardianes de la Galaxia", "Guardians of the Galaxy Bald Nebula"),
                  ("Superchica", "Supergirl"),
                #   ("Mujer Araña", "Spiderwoman"), 
                #   ("Irongirl"), 
                #   ("Spidergwen"),
                #   ("Spider Gwen"),
                #   ("Susan Storm"),                    
                  ("Gatúbela", "Catwoman"),
                  # ("Mujer Invisible", "Invisible Woman"), 
                  ("Mujer Invisible", "Invisible Woman Susan Storm"),   
                  # ("Mujer Invisible", "Invisible Woman Fantastic 4"),                 
                  # ("Superheroina Sin Máscara", "Unmasked Superheroine"),
                  ("Viuda Negra", "Black Widow"),
                  # ("Xmen Jubilee"),
                  ("Psylocke", "Psylocke with katanas"),
                  # ("Elektra", "Elektra Natchios with sai"),   
                  ("She-Hulk"),
                  ("Powergirl"),
                  ("DC's Powergirl"),   
                  ("Harley Quinn"),   
                  ("Hiedra Venenosa", "Poison Ivy"),
                  # ("Reina Blanca", "White Queen"), 
                  ("Reina Blanca", "White Queen Emma Frost"), #OK!
                  # ("Reina Blanca", "Emma Frost"), 
                  ("Reina Blanca", "Marvel's White Queen"), #OK!!
                  ("Reina Blanca", "Marvel's Emma Frost"),
                  # ("Domino", "Marvel's Domino"), 
                  ("Jean Grey", "Marvel's Jean Grey"),
                  ("Jean Grey", "Xmen Jean Grey")                            
                  ]

super_heroes = [
                  ("Batman"),
                  ("Bruce Wayne Batman"), 
                  ("Batman sin máscara", "Unmasked Batman"),
                  ("Dr.Strange"),
                  ("Flash Gordon"),
                  ("Linterna Verde", "Green Lantern"),
                  ("Hawkeye"), 
                  ("Antorcha Humana", "Human Torch"),
                  ("Shazam"),
                  ("Hulk"),
                  ("StarLord"),
                  ("Superman"),                  
                  ("Tony Stark"),
                  ("Tony Stark Ironman"),  
                  ("Ironman sin máscara", "Unmasked Ironman"), 
                  ("Hombre Araña", "Spiderman"), 
                  ("Ironman"),
                  ("Hombre de Acero", "Ironman"), 
                  ("Peter Parker"),
                  ("Hombre Araña sin máscara", "Spiderman Peter Parker"),
                  ("Flash"),                    
                  ("Robin"),
                  ("Robin Sin Máscara", "Unmasked Robin"),
                  ("Ozymandias de Watchen", "Watchmen Ozymandias"),                  
                  ("Superheroe sin máscara", "Unmasked Superhero"),  
                  ("Colossus", "Xmen Colossus")             
                  ]