name: Splashmix Dev 👾

on:
    push:
        branches:
            - dev
jobs:
    run_pull:
        name: run pull 
        runs-on: ubuntu-latest

        steps:
        - name: install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
           
        - name: connect and pull
          run: | 
              ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "cd ${{ secrets.DEV_WORK_DIR }} && git checkout ${{ secrets.DEV_BRANCH }} \
              && git pull origin main \
              && source venv/bin/activate \
              && pip install -r requirements.txt \
              && exit"
                
        - name: cleanup
          run: rm -rf ~/.ssh